title: My Cool Site
description: Built with the BlueStar Jekyll Theme


remote_theme: zbule/bluestar-theme

plugins:
  - jekyll-remote-theme
 # - jekyll-feed
 # - jekyll-seo-tag

# Optional: site navigation, social links, etc.
