title: My Cool Site
description: Built with the BlueStar Jekyll Theme
baseurl: "" # leave empty or set to your subpath
url: "https://mycooldomain.com"

remote_theme: zbule/bluestar-theme

plugins:
  - jekyll-remote-theme
 # - jekyll-feed
 # - jekyll-seo-tag

# Optional: site navigation, social links, etc.
